from __future__ import annotations

from datetime import datetime
from pathlib import Path

from dotenv import load_dotenv

ROOT = Path(__file__).resolve().parent
load_dotenv(ROOT / ".env")


def timestamp() -> str:
    return datetime.now().strftime("%Y-%m-%d %H:%M")


def activity_entry(message: str) -> str:
    return f"{timestamp()} | {message}"


WORKERS = [
    {
        "id": "w-001",
        "name": "张师傅",
        "email": "zhang.worker@example.com",
        "area": "North Shore",
        "phone": "021-900-1001",
        "approvalStatus": "approved",
        "serviceNote": "擅长大面积主体割草后的边缘收尾，适合北岸独立屋。",
        "available": True,
        "lat": -36.726,
        "lng": 174.698,
    },
    {
        "id": "w-002",
        "name": "李师傅",
        "email": "li.worker@example.com",
        "area": "Mt Eden / Epsom",
        "phone": "021-900-1002",
        "approvalStatus": "approved",
        "serviceNote": "擅长规则草坪和花坛边人工修整，沟通响应快。",
        "available": True,
        "lat": -36.875,
        "lng": 174.763,
    },
    {
        "id": "w-003",
        "name": "王师傅",
        "email": "wang.worker@example.com",
        "area": "Howick / Botany",
        "phone": "021-900-1003",
        "approvalStatus": "probation",
        "serviceNote": "当前以东区订单为主，复杂院落需要平台先复核照片。",
        "available": False,
        "lat": -36.903,
        "lng": 174.932,
    },
    {
        "id": "w-004",
        "name": "陈师傅",
        "email": "chen.worker@example.com",
        "area": "Henderson / Westgate",
        "phone": "021-900-1004",
        "approvalStatus": "approved",
        "serviceNote": "西区订单经验较多，树下和墙边补刀处理稳定。",
        "available": True,
        "lat": -36.865,
        "lng": 174.627,
    },
]

SEED_ORDERS = [
    {
        "id": "MOW-1001",
        "user": "Helen Chen",
        "phone": "021-000-1001",
        "address": "16 Pounamu Place, Auckland",
        "serviceType": "一次性割草",
        "requestedTime": "2026-06-10 09:00-12:00",
        "lawnSize": "约 220 平方米",
        "condition": "前院规则，后院树多，靠围栏处边缘复杂",
        "note": "门在左侧小路，院内有一只小狗，服务前请电话确认。",
        "status": "pending_review",
        "priorityLevel": "high",
        "opsTag": "树下补刀",
        "price": "",
        "priceNote": "",
        "assignedWorkerId": "",
        "actualAmount": "",
        "paymentStatus": "unpaid",
        "paymentMethod": "",
        "paymentReceivedAt": "",
        "paymentNote": "",
        "settlementStatus": "pending",
        "completionNote": "",
        "reviewNote": "",
        "exceptionType": "",
        "exceptionNote": "",
        "exceptionResolution": "",
        "platformShare": "",
        "workerPayout": "",
        "settledAt": "",
        "updatedAt": "2026-06-08 16:30",
        "photos": ["前院参考", "后院树下", "围栏边缘"],
        "activity": ["用户提交订单，等待平台确认价格和时间。"],
        "internalNote": "",
    },
    {
        "id": "MOW-1002",
        "user": "Michael Lee",
        "phone": "021-000-1002",
        "address": "88 Landscape Road, Mt Eden",
        "serviceType": "定期割草预约",
        "requestedTime": "2026-06-11 13:00-16:00",
        "lawnSize": "约 160 平方米",
        "condition": "草坪较平整，花坛边需要人工修整",
        "note": "希望每两周一次，第一次服务后确认长期价格。",
        "status": "quoted",
        "priorityLevel": "normal",
        "opsTag": "定期客户",
        "price": "95",
        "priceNote": "规则草坪，含花坛边人工修整。",
        "assignedWorkerId": "",
        "actualAmount": "",
        "paymentStatus": "unpaid",
        "paymentMethod": "",
        "paymentReceivedAt": "",
        "paymentNote": "",
        "settlementStatus": "pending",
        "completionNote": "",
        "reviewNote": "",
        "exceptionType": "",
        "exceptionNote": "",
        "exceptionResolution": "",
        "platformShare": "",
        "workerPayout": "",
        "settledAt": "",
        "updatedAt": "2026-06-08 15:20",
        "photos": ["入口照片", "主草坪", "花坛边"],
        "activity": ["平台完成报价：$95。", "等待用户确认或运营继续派单。"],
        "internalNote": "",
    },
    {
        "id": "MOW-1003",
        "user": "Sarah Wang",
        "phone": "021-000-1003",
        "address": "21 Pine Street, Albany",
        "serviceType": "一次性割草",
        "requestedTime": "2026-06-10 14:00-17:00",
        "lawnSize": "约 300 平方米",
        "condition": "后院面积大，边角多，机器人适合处理主体区域",
        "note": "后门密码已通过短信发送给客服。",
        "status": "assigned",
        "priorityLevel": "urgent",
        "opsTag": "大院复杂边角",
        "price": "145",
        "priceNote": "面积较大，包含较多边角收尾。",
        "assignedWorkerId": "w-001",
        "actualAmount": "",
        "paymentStatus": "unpaid",
        "paymentMethod": "",
        "paymentReceivedAt": "",
        "paymentNote": "",
        "settlementStatus": "pending",
        "completionNote": "",
        "reviewNote": "",
        "exceptionType": "",
        "exceptionNote": "",
        "exceptionResolution": "",
        "platformShare": "",
        "workerPayout": "",
        "settledAt": "",
        "updatedAt": "2026-06-08 14:45",
        "photos": ["前院", "大面积后院", "角落区域"],
        "activity": ["平台完成报价：$145。", "订单已派给张师傅。"],
        "internalNote": "",
    },
    {
        "id": "MOW-1004",
        "user": "David Smith",
        "phone": "021-000-1004",
        "address": "5 Garden Lane, Henderson",
        "serviceType": "一次性割草",
        "requestedTime": "2026-06-12 10:00-12:00",
        "lawnSize": "约 120 平方米",
        "condition": "小块草坪，墙边和树下需要人工处理",
        "note": "客户强调树下区域要修整干净。",
        "status": "accepted_by_worker",
        "priorityLevel": "normal",
        "opsTag": "树下精修",
        "price": "85",
        "priceNote": "小面积，人工精细收尾占比较高。",
        "assignedWorkerId": "w-004",
        "actualAmount": "",
        "paymentStatus": "unpaid",
        "paymentMethod": "",
        "paymentReceivedAt": "",
        "paymentNote": "",
        "settlementStatus": "pending",
        "completionNote": "",
        "reviewNote": "",
        "exceptionType": "",
        "exceptionNote": "",
        "exceptionResolution": "",
        "platformShare": "",
        "workerPayout": "",
        "settledAt": "",
        "updatedAt": "2026-06-08 13:05",
        "photos": ["入口", "树下", "墙边"],
        "activity": ["平台完成报价：$85。", "订单已派给陈师傅。", "陈师傅已确认接单。"],
        "internalNote": "",
    },
    {
        "id": "MOW-1005",
        "user": "Anna Brown",
        "phone": "021-000-1005",
        "address": "42 Valley View Road, Howick",
        "serviceType": "一次性割草",
        "requestedTime": "2026-06-09 09:00-11:00",
        "lawnSize": "约 260 平方米",
        "condition": "草较高，可能需要额外处理",
        "note": "客户临时改期，等待平台重新确认。",
        "status": "cancelled",
        "priorityLevel": "low",
        "opsTag": "待改期",
        "price": "130",
        "priceNote": "草较高，原报价含额外处理。",
        "assignedWorkerId": "w-003",
        "actualAmount": "",
        "paymentStatus": "unpaid",
        "paymentMethod": "",
        "paymentReceivedAt": "",
        "paymentNote": "",
        "settlementStatus": "pending",
        "completionNote": "",
        "reviewNote": "",
        "exceptionType": "",
        "exceptionNote": "",
        "exceptionResolution": "",
        "platformShare": "",
        "workerPayout": "",
        "settledAt": "",
        "updatedAt": "2026-06-08 11:40",
        "photos": ["草况", "入口", "侧边"],
        "activity": ["平台完成报价：$130。", "原订单已取消，等待用户重新预约。"],
        "internalNote": "",
    },
]
